version: "3.7"
services:
  database:
    container_name: database_container
    image: postgres
    restart: always
    networks:
      new:
        aliases:
          - database_container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - ./migrations:/migrations
    command:
      [ "-path", "/migrations", "-database",  "postgres://barqus:root@database_container:5432/fillq-db?sslmode=disable", "up" ]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - new
    ports:
      - "8080:8080"
  scheduler:
    build:
      context: .
      dockerfile: DockerfileScheduler
    env_file: .env
    depends_on:
      - database
    networks:
      - new
volumes:
  data:
networks:
  new: